//+------------------------------------------------------------------+
//|                                                  XAU_Profit_EA   |
//|                                     Prosty EA dla MetaTrader 5   |
//|  Wejścia: EMA + wybicie swingów, TP/SL jako % ceny, risk-based   |
//+------------------------------------------------------------------+
#property copyright "Generated by Assistant"
#property version   "1.0"
#property strict

#include <Trade/Trade.mqh>

input string   InpSymbol            = "";          // Symbol (puste = bieżący)
input ENUM_TIMEFRAMES InpTimeframe  = PERIOD_CURRENT; // Interwał (PERIOD_CURRENT = wykres)
input double   InpRiskPercent       = 1.0;         // Ryzyko na transakcję (% salda)
input double   InpTP_Percent        = 1.50;        // Take Profit (% ceny)
input double   InpSL_Percent        = 0.75;        // Stop Loss (% ceny)
input bool     InpUseTrailingStop   = true;        // Włącz trailing stop
input double   InpTrailPercent      = 0.60;        // Trailing (% ceny, dystans od bieżącej)
input int      InpTrailStepPoints   = 50;          // Min. krok modyfikacji SL (w punktach)
input int      InpMAPeriod          = 50;          // EMA okres
input int      InpBreakoutLookback  = 20;          // Wybicie: liczba barów wstecz
input int      InpMaxSpreadPoints   = 200;         // Maks. spread (w punktach)
input int      InpDeviationPoints   = 20;          // Maks. odchylenie (w punktach)
input bool     InpAllowLong         = true;        // Zezwalaj na long
input bool     InpAllowShort        = true;        // Zezwalaj na short
input int      InpTradeStartHour    = 0;           // Godzina start (0-23)
input int      InpTradeEndHour      = 24;          // Godzina koniec (1-24)

CTrade trade;
string  g_symbol;
int     g_digits;
double  g_point;
datetime g_lastBarTime = 0;

//--- Pomocnicze -----------------------------------------------------
bool IsNewBar()
{
  datetime t = iTime(g_symbol, InpTimeframe, 0);
  if (t != 0 && t != g_lastBarTime)
  {
    g_lastBarTime = t;
    return true;
  }
  return false;
}

bool IsTradingHour()
{
  int hour = TimeHour(TimeCurrent());
  int startH = MathMax(0, MathMin(23, InpTradeStartHour));
  int endH   = MathMax(1, MathMin(24, InpTradeEndHour));
  if (startH < endH)
    return (hour >= startH && hour < endH);
  // okno przez północ
  return (hour >= startH || hour < endH);
}

double PercentToPoints(double percent, double price)
{
  if (percent <= 0.0) return 0.0;
  double points = (price * (percent / 100.0)) / g_point;
  return points;
}

double NormalizePrice(double price)
{
  return NormalizeDouble(price, g_digits);
}

double NormalizeVolume(const string sym, double lots)
{
  double volMin  = SymbolInfoDouble(sym, SYMBOL_VOLUME_MIN);
  double volMax  = SymbolInfoDouble(sym, SYMBOL_VOLUME_MAX);
  double volStep = SymbolInfoDouble(sym, SYMBOL_VOLUME_STEP);
  if (volStep <= 0.0) volStep = 0.01;
  // Zaokrąglanie do kroku
  double steps = MathRound(lots / volStep);
  double norm  = steps * volStep;
  if (norm < volMin) norm = volMin;
  if (norm > volMax) norm = volMax;
  return norm;
}

bool SpreadAcceptable()
{
  double ask = SymbolInfoDouble(g_symbol, SYMBOL_ASK);
  double bid = SymbolInfoDouble(g_symbol, SYMBOL_BID);
  if (ask == 0.0 || bid == 0.0) return false;
  double spreadPts = (ask - bid) / g_point;
  return (spreadPts <= InpMaxSpreadPoints);
}

bool EnsureStopsDistanceOK(double entryPrice, double &slPrice, double &tpPrice, bool isBuy)
{
  int stopsLevel = (int)SymbolInfoInteger(g_symbol, SYMBOL_TRADE_STOPS_LEVEL);
  if (stopsLevel < 0) stopsLevel = 0;
  double minDist = stopsLevel * g_point;
  if (isBuy)
  {
    if (entryPrice - slPrice < minDist) slPrice = entryPrice - minDist;
    if (tpPrice - entryPrice < minDist) tpPrice = entryPrice + minDist;
  }
  else
  {
    if (slPrice - entryPrice < minDist) slPrice = entryPrice + minDist;
    if (entryPrice - tpPrice < minDist) tpPrice = entryPrice - minDist;
  }
  slPrice = NormalizePrice(slPrice);
  tpPrice = NormalizePrice(tpPrice);
  return true;
}

bool HasOpenPosition()
{
  if (!PositionSelect(g_symbol)) return false;
  return true;
}

int CurrentPositionType() // -1 none, 0 buy, 1 sell
{
  if (!PositionSelect(g_symbol)) return -1;
  long type = (long)PositionGetInteger(POSITION_TYPE);
  return (type == POSITION_TYPE_BUY) ? 0 : 1;
}

// Oblicza wielkość pozycji z ryzyka i odległości SL (w punktach)
double CalculatePositionSize(double stopLossPoints)
{
  if (stopLossPoints <= 0.0) return 0.0;
  double balance   = AccountInfoDouble(ACCOUNT_BALANCE);
  double riskMoney = balance * (InpRiskPercent / 100.0);

  double tickValue = SymbolInfoDouble(g_symbol, SYMBOL_TRADE_TICK_VALUE);
  double tickSize  = SymbolInfoDouble(g_symbol, SYMBOL_TRADE_TICK_SIZE);
  if (tickSize <= 0.0) tickSize = g_point; // fallback

  double valuePerPointFor1Lot = (tickValue / tickSize) * g_point; // wartość 1 punktu dla 1 lota
  if (valuePerPointFor1Lot <= 0.0) return 0.0;

  double lots = riskMoney / (stopLossPoints * valuePerPointFor1Lot);
  lots = NormalizeVolume(g_symbol, lots);
  return lots;
}

// Sygnały: EMA + wybicie swingów
bool SignalBuy()
{
  if (!InpAllowLong) return false;
  // Używamy zamkniętej świecy (shift=1)
  double emaPrev = iMA(g_symbol, InpTimeframe, InpMAPeriod, 0, MODE_EMA, PRICE_CLOSE, 1);
  double closePrev = iClose(g_symbol, InpTimeframe, 1);
  if (emaPrev == 0.0 || closePrev == 0.0) return false;
  if (closePrev <= emaPrev) return false;

  // Wybicie ponad ostatni swing high z okna [1..InpBreakoutLookback]
  int hhShift = iHighest(g_symbol, InpTimeframe, MODE_HIGH, InpBreakoutLookback, 1);
  if (hhShift < 0) return false;
  double lastHH = iHigh(g_symbol, InpTimeframe, hhShift);
  if (lastHH == 0.0) return false;
  return (closePrev > lastHH);
}

bool SignalSell()
{
  if (!InpAllowShort) return false;
  double emaPrev = iMA(g_symbol, InpTimeframe, InpMAPeriod, 0, MODE_EMA, PRICE_CLOSE, 1);
  double closePrev = iClose(g_symbol, InpTimeframe, 1);
  if (emaPrev == 0.0 || closePrev == 0.0) return false;
  if (closePrev >= emaPrev) return false;

  int llShift = iLowest(g_symbol, InpTimeframe, MODE_LOW, InpBreakoutLookback, 1);
  if (llShift < 0) return false;
  double lastLL = iLow(g_symbol, InpTimeframe, llShift);
  if (lastLL == 0.0) return false;
  return (closePrev < lastLL);
}

// Otwarcie pozycji
bool OpenPosition(bool isBuy)
{
  double ask = SymbolInfoDouble(g_symbol, SYMBOL_ASK);
  double bid = SymbolInfoDouble(g_symbol, SYMBOL_BID);
  if (ask == 0.0 || bid == 0.0) return false;

  double entry = isBuy ? ask : bid;
  double tpPts = PercentToPoints(InpTP_Percent, entry);
  double slPts = PercentToPoints(InpSL_Percent, entry);
  if (tpPts <= 0.0 || slPts <= 0.0) return false;

  double sl = isBuy ? entry - slPts * g_point : entry + slPts * g_point;
  double tp = isBuy ? entry + tpPts * g_point : entry - tpPts * g_point;
  EnsureStopsDistanceOK(entry, sl, tp, isBuy);

  // Przelicz ryzyko wg rzeczywistej odległości SL po korekcie stops level
  double actualSLPts = (isBuy ? (entry - sl) : (sl - entry)) / g_point;
  if (actualSLPts <= 0.0) return false;
  double lots = CalculatePositionSize(actualSLPts);
  if (lots <= 0.0)
  {
    Print("CalculatePositionSize zwróciło 0. Brak otwarcia.");
    return false;
  }

  trade.SetDeviationInPoints(InpDeviationPoints);
  bool ok = isBuy ? trade.Buy(lots, g_symbol, entry, sl, tp, "XAU_Profit_EA")
                  : trade.Sell(lots, g_symbol, entry, sl, tp, "XAU_Profit_EA");
  if (!ok)
  {
    PrintFormat("Błąd zlecenia %s: %d (%s)",
                isBuy ? "Buy" : "Sell",
                GetLastError(),
                ErrorDescription(GetLastError()));
  }
  return ok;
}

// Zarządzanie pozycją: jeśli sygnał przeciwny i tryb netting – zamknij i odwróć
void ManageExistingPosition()
{
  if (!PositionSelect(g_symbol)) return;
  long posType = PositionGetInteger(POSITION_TYPE);
  ulong ticket  = (ulong)PositionGetInteger(POSITION_TICKET);

  bool wantBuy  = SignalBuy();
  bool wantSell = SignalSell();

  // Netting: tylko 1 pozycja – jeśli sygnał przeciwny, zamknij i ewentualnie otwórz w drugą stronę
  if (posType == POSITION_TYPE_BUY && wantSell)
  {
    trade.PositionClose(ticket);
    // Otwórz sell, jeśli wciąż aktualny
    if (SpreadAcceptable() && IsTradingHour())
      OpenPosition(false);
  }
  else if (posType == POSITION_TYPE_SELL && wantBuy)
  {
    trade.PositionClose(ticket);
    if (SpreadAcceptable() && IsTradingHour())
      OpenPosition(true);
  }
  else
  {
    // Brak sygnału odwrócenia – spróbuj dociągnąć SL trailingiem
    if (InpUseTrailingStop)
      ApplyTrailingStop();
  }
}

// Trailing stop: zacieśnia SL o zadany % ceny z minimalnym krokiem
void ApplyTrailingStop()
{
  if (!PositionSelect(g_symbol)) return;
  long posType = PositionGetInteger(POSITION_TYPE);
  double sl    = PositionGetDouble(POSITION_SL);
  double tp    = PositionGetDouble(POSITION_TP);

  double price = (posType == POSITION_TYPE_BUY)
                 ? SymbolInfoDouble(g_symbol, SYMBOL_BID)
                 : SymbolInfoDouble(g_symbol, SYMBOL_ASK);
  if (price <= 0.0) return;

  double trailPts = PercentToPoints(InpTrailPercent, price);
  if (trailPts <= 0.0) return;

  double proposedSL = (posType == POSITION_TYPE_BUY)
                      ? price - trailPts * g_point
                      : price + trailPts * g_point;
  proposedSL = NormalizePrice(proposedSL);

  // Nie pogarszaj SL i zachowaj minimalny krok
  if (sl > 0.0)
  {
    if (posType == POSITION_TYPE_BUY)
    {
      if (proposedSL <= sl + InpTrailStepPoints * g_point) return;
      if (proposedSL >= price) return;
    }
    else
    {
      if (proposedSL >= sl - InpTrailStepPoints * g_point) return;
      if (proposedSL <= price) return;
    }
  }
  else
  {
    // Jeżeli SL nie ustawiony (nie powinno się zdarzyć), nie ustawiaj go nad/pod rynkiem
    if ((posType == POSITION_TYPE_BUY && proposedSL >= price) ||
        (posType == POSITION_TYPE_SELL && proposedSL <= price))
      return;
  }

  // Sprawdź minimalne odległości od bieżącej ceny
  double checkSL = proposedSL, checkTP = tp;
  EnsureStopsDistanceOK(price, checkSL, checkTP, (posType == POSITION_TYPE_BUY));

  // Jeżeli po korekcie nie ma progresu względem obecnego SL – pomiń
  if (sl > 0.0)
  {
    if (posType == POSITION_TYPE_BUY && checkSL <= sl) return;
    if (posType == POSITION_TYPE_SELL && checkSL >= sl) return;
  }

  trade.PositionModify(g_symbol, checkSL, tp);
}

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
  g_symbol = (InpSymbol == "" ? _Symbol : InpSymbol);
  if (!SymbolInfoInteger(g_symbol, SYMBOL_SELECT))
  {
    if (!SymbolSelect(g_symbol, true))
    {
      Print("Nie można wybrać symbolu: ", g_symbol);
      return INIT_FAILED;
    }
  }
  g_digits = (int)SymbolInfoInteger(g_symbol, SYMBOL_DIGITS);
  g_point  = SymbolInfoDouble(g_symbol, SYMBOL_POINT);
  if (g_point <= 0.0)
  {
    Print("Błędny punkt dla symbolu: ", g_symbol);
    return INIT_FAILED;
  }
  g_lastBarTime = iTime(g_symbol, InpTimeframe, 0);
  return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
  // nic
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
  if (!IsTradingHour()) return;
  if (!SpreadAcceptable()) return;

  // Pracuj na zamknięciach świec (unika wielokrotnych wejść)
  if (!IsNewBar()) return;

  // Jeśli jest pozycja – zarządzaj i ewentualnie odwróć
  if (HasOpenPosition())
  {
    ManageExistingPosition();
    return;
  }

  // Jeśli nie ma pozycji – szukaj nowego wejścia
  bool buy  = SignalBuy();
  bool sell = SignalSell();

  if (buy && InpAllowLong)
  {
    OpenPosition(true);
    return;
  }
  if (sell && InpAllowShort)
  {
    OpenPosition(false);
    return;
  }
}

//+------------------------------------------------------------------+
