/** UI copy — English (default site language) and Polish. Story modal body stays English. */

export const STRINGS = {
  en: {
    nav_socialAria: 'Social and charts',
    hero_title: 'HopeKids',
    hero_tagline: 'Support sick children through cryptocurrency.',
    hero_bodyBefore: 'When you buy or trade HKIDS, part of every swap supports sick children.',
    hero_bodyPercent: '3%',
    hero_bodyAfter: 'of each transaction goes to the public donation wallet.',
    hero_buy: 'Buy HopeKids',
    hero_wallet: 'View Donation Wallet',
    stats_tokensSaved: 'Tokens Saved for Children',
    stats_currentValue: 'Current Value',
    stats_txs: 'Total Transactions Helping Children',
    market_title: 'Live market (DexScreener)',
    market_charts: 'Charts & pair ↗',
    market_holders: 'Holders on DexScreener ↗',
    market_cap: 'Market cap',
    market_price: 'Price',
    market_liq: 'Liquidity',
    jupiter_title: 'Swap on Jupiter',
    jupiter_body:
      'Trade SOL for HKIDS in one flow. Opens the official Jupiter swap in a new tab — same route as the Buy button.',
    jupiter_cta: 'Open Jupiter swap ↗',
    fundraiser_title: 'Fundraiser',
    fundraiser_body:
      'A HopeKids fundraiser for children who need care. Share the page, donate to the public wallet, or get HKIDS — every contribution supports the mission.',
    support_window: 'Support window',
    support_cycle: '30-day cycle · hours shown first',
    support_title: 'Support the project',
    support_growth: 'Growth ideas',
    support_growthBody:
      '— new campaigns, better storytelling, or features that make donating and tracking impact easier.',
    support_partners: 'Partnerships',
    support_partnersBody: '— brands, creators, hospitals, or NGOs that share the mission and want to co-create reach or events.',
    support_build: 'Build & ship',
    support_buildBody:
      '— developers, designers, or volunteers who can help improve the site, wallet flows, or transparency tools.',
    support_spread: 'Spread the word',
    support_spreadBody:
      '— share on socials, invite communities, and point people to the public donation wallet and HKIDS.',
    mission_title: 'Mission — What is HopeKids?',
    mission_sub: 'A movement of hope — tap to read our full story.',
    mission_open: 'Open',
    transparency_title: 'Transparency',
    wallet_title: 'Public Donation Wallet',
    wallet_verify: 'Verify on Solscan ↗',
    wallet_verifyHint: 'Inspect the public donation address on-chain (read-only).',
    wallet_recent: 'Recent signatures',
    wallet_recentEmpty: 'No recent data (try again on the deployed site).',
    wallet_recentErr: 'Could not load activity.',
    contact_title: 'Contact the team',
    contact_body: 'Questions, partnerships, or support — email us. We respond to HopeKids-related messages.',
    footer_rights: 'HopeKids © 2026',
    footer_tagline: 'Trade crypto. Give hope.',
    faq_title: 'FAQ',
    faq_q1: 'What is HKIDS?',
    faq_a1:
      'HKIDS is the HopeKids token on Solana. Buying or trading it helps fund the mission; part of swap flow goes to the public donation wallet.',
    faq_q2: 'Where does the 3% go?',
    faq_a2:
      'A protocol fee from each transaction is directed to the published donation wallet. You can verify the address and on-chain activity yourself.',
    faq_q3: 'Is the donation wallet public?',
    faq_a3:
      'Yes. The address is listed on this page. We do not hide it — transparency is the point.',
    faq_q4: 'How do I get HKIDS?',
    faq_a4:
      'Use the Buy / Jupiter link to swap SOL for HKIDS, or receive tokens from another wallet. Always double-check the mint address.',
    privacy_title: 'Privacy',
    privacy_p1:
      'This page is informational. We do not require an account to read it. If you email us, we use your address only to reply about HopeKids.',
    privacy_p2:
      'The site may use privacy-friendly analytics (e.g. Vercel) to understand traffic — no ads profile. You can use browser controls or extensions to limit tracking.',
    privacy_p3:
      'For EU/EEA users: you may request access or deletion of correspondence by contacting the team email below.',
    tools_lang: 'Language',
    tools_contrast: 'High contrast',
    tools_help: 'Shortcuts',
    tools_en: 'EN',
    tools_pl: 'PL',
    shortcuts_title: 'Keyboard shortcuts',
    shortcuts_esc: 'Close dialogs / modals',
    shortcuts_slash: 'Open this help panel',
    shortcuts_close: 'Close',
    copy_done: 'Copied to clipboard',
    copy_aria: 'Copy wallet address',
    copy_ariaDone: 'Copied',
    story_title: 'The HopeKids story',
    story_close: 'Close',
    email_aria: 'Email HopeKids at',
    timer_aria: 'Time remaining in this 30-day support window',
    section_fundraiserAria: 'Fundraiser spotlight and supporting the project',
    section_marketAria: 'HKIDS live market data from DexScreener',
    intro_aria: 'HopeKids introduction',
    spotlight_alt: 'Example HopeKids spotlight child (illustrative photo)',
  },
  pl: {
    nav_socialAria: 'Social media i wykresy',
    hero_title: 'HopeKids',
    hero_tagline: 'Wspieraj chore dzieci dzięki kryptowalutom.',
    hero_bodyBefore: 'Gdy kupujesz lub handlujesz HKIDS, część każdej zamiany trafia na pomoc dzieciom.',
    hero_bodyPercent: '3%',
    hero_bodyAfter: 'każdej transakcji trafia do publicznego portfela darowizn.',
    hero_buy: 'Kup HopeKids',
    hero_wallet: 'Zobacz portfel darowizn',
    stats_tokensSaved: 'Tokeny zebrane dla dzieci',
    stats_currentValue: 'Aktualna wartość',
    stats_txs: 'Transakcje wspierające dzieci',
    market_title: 'Rynek na żywo (DexScreener)',
    market_charts: 'Wykresy i para ↗',
    market_holders: 'Holderzy na DexScreener ↗',
    market_cap: 'Kapitalizacja',
    market_price: 'Cena',
    market_liq: 'Płynność',
    jupiter_title: 'Zamiana na Jupiter',
    jupiter_body:
      'Wymień SOL na HKIDS w jednym przejściu. Otwiera oficjalną zamianę Jupiter w nowej karcie — ten sam szlak co przycisk Kup.',
    jupiter_cta: 'Otwórz Jupiter ↗',
    fundraiser_title: 'Zbiórka',
    fundraiser_body:
      'Zbiórka HopeKids dla dzieci potrzebujących opieki. Udostępnij stronę, wpłać na publiczny portfel lub zdobądź HKIDS — każdy wkład wspiera misję.',
    support_window: 'Okno wsparcia',
    support_cycle: 'Cykl 30 dni · najpierw godziny',
    support_title: 'Wesprzyj projekt',
    support_growth: 'Pomysły na rozwój',
    support_growthBody:
      '— nowe kampanie, lepszy storytelling lub funkcje ułatwiające darowizny i śledzenie efektów.',
    support_partners: 'Partnerstwa',
    support_partnersBody:
      '— marki, twórcy, szpitale lub NGO dzielące misję i chcące współtworzyć zasięg lub wydarzenia.',
    support_build: 'Budowa i wdrożenia',
    support_buildBody:
      '— deweloperzy, designerzy lub wolontariusze pomagający w stronie, portfelu i narzędziach transparentności.',
    support_spread: 'Dotrzyj ze słowem',
    support_spreadBody:
      '— udostępniaj w socialach, zapraszaj społeczności, wskazuj publiczny portfel darowizn i HKIDS.',
    mission_title: 'Misja — czym jest HopeKids?',
    mission_sub: 'Ruch nadziei — dotknij, by przeczytać całą historię.',
    mission_open: 'Otwórz',
    transparency_title: 'Transparentność',
    wallet_title: 'Publiczny portfel darowizn',
    wallet_verify: 'Sprawdź na Solscan ↗',
    wallet_verifyHint: 'Podgląd publicznego adresu w łańcuchu (tylko odczyt).',
    wallet_recent: 'Ostatnie podpisy',
    wallet_recentEmpty: 'Brak danych (spróbuj na wdrożonej stronie).',
    wallet_recentErr: 'Nie udało się wczytać aktywności.',
    contact_title: 'Kontakt z zespołem',
    contact_body: 'Pytania, partnerstwa lub wsparcie — napisz maila. Odpowiadamy w sprawach HopeKids.',
    footer_rights: 'HopeKids © 2026',
    footer_tagline: 'Handluj krypto. Dawaj nadzieję.',
    faq_title: 'FAQ',
    faq_q1: 'Czym jest HKIDS?',
    faq_a1:
      'HKIDS to token HopeKids w sieci Solana. Kupno lub handel wspiera misję; część przepływu zamiany trafia do publicznego portfela darowizn.',
    faq_q2: 'Dokąd trafia 3%?',
    faq_a2:
      'Opłata protokołu z transakcji jest kierowana do opublikowanego portfela darowizn. Adres i aktywność w łańcuchu możesz zweryfikować samodzielnie.',
    faq_q3: 'Czy portfel darowizn jest publiczny?',
    faq_a3:
      'Tak. Adres jest na tej stronie. Nie ukrywamy go — o to chodzi w transparentności.',
    faq_q4: 'Jak zdobyć HKIDS?',
    faq_a4:
      'Użyj linku Kup / Jupiter, by zamienić SOL na HKIDS, lub otrzymaj tokeny z innego portfela. Zawsze sprawdź adres mint.',
    privacy_title: 'Prywatność',
    privacy_p1:
      'Ta strona ma charakter informacyjny. Nie wymaga konta. Jeśli napiszesz maila, używamy adresu tylko do odpowiedzi w sprawie HopeKids.',
    privacy_p2:
      'Strona może używać przyjaznej analityki (np. Vercel) do statystyk ruchu — bez profilu pod reklamy. Możesz ograniczyć śledzenie ustawieniami przeglądarki.',
    privacy_p3:
      'Dla użytkowników UE/EOG: możesz poprosić o dostęp lub usunięcie korespondencji przez e-mail zespołu poniżej.',
    tools_lang: 'Język',
    tools_contrast: 'Wysoki kontrast',
    tools_help: 'Skróty',
    tools_en: 'EN',
    tools_pl: 'PL',
    shortcuts_title: 'Skróty klawiszowe',
    shortcuts_esc: 'Zamyka okna / modale',
    shortcuts_slash: 'Otwiera ten panel pomocy',
    shortcuts_close: 'Zamknij',
    copy_done: 'Skopiowano do schowka',
    copy_aria: 'Kopiuj adres portfela',
    copy_ariaDone: 'Skopiowano',
    story_title: 'Historia HopeKids',
    story_close: 'Zamknij',
    email_aria: 'Napisz do HopeKids:',
    timer_aria: 'Pozostały czas w 30-dniowym oknie wsparcia',
    section_fundraiserAria: 'Zbiórka i wsparcie projektu',
    section_marketAria: 'Dane rynkowe HKIDS z DexScreener',
    intro_aria: 'Wprowadzenie HopeKids',
    spotlight_alt: 'Przykładowe zdjęcie dziecka w spotlight HopeKids (ilustracyjne)',
  },
};

export function createT(locale) {
  const L = STRINGS[locale] || STRINGS.en;
  const fallback = STRINGS.en;
  return (key) => L[key] ?? fallback[key] ?? key;
}
