/** UI copy — English default; pl, ru, tr, de, hi. Story modal narrative body stays English. */

export const STRINGS = {
  en: {
    nav_socialAria: 'Social and charts',
    hero_title: 'HopeKids',
    hero_tagline: 'Support sick children through cryptocurrency.',
    hero_bodyBefore: 'On every HKIDS trade,',
    hero_bodyPercent: '3%',
    hero_bodyAfter:
      'of the activity is routed as HopeKids (HKIDS) tokens to the public donation wallet. If you send HKIDS or SOL to that address yourself, the full amount is donated to the fundraiser — nothing is withheld.',
    hero_buy: 'Buy HopeKids',
    hero_wallet: 'View Donation Wallet',
    stats_tokensSaved: 'Tokens Saved for Children',
    stats_currentValue: 'Current Value',
    stats_txs: 'Total Transactions Helping Children',
    market_title: 'Live market (DexScreener)',
    market_charts: 'Charts & pair ↗',
    market_holders: 'Holders on DexScreener ↗',
    market_cap: 'Market cap',
    market_price: 'Price',
    market_liq: 'Liquidity',
    jupiter_title: 'Swap on Jupiter',
    jupiter_body:
      'Trade SOL for HKIDS in one flow. Opens the official Jupiter swap in a new tab — same route as the Buy button.',
    jupiter_cta: 'Open Jupiter swap ↗',
    fundraiser_title: 'Fundraiser',
    fundraiser_body:
      'A HopeKids fundraiser for children who need care. Share the page, trade HKIDS, or transfer HKIDS or SOL to the public wallet — swap flow sends 3% as HKIDS to that wallet; direct transfers are credited in full.',
    support_window: 'Support window',
    support_cycle: '30-day cycle · hours shown first',
    support_title: 'Support the project',
    support_growth: 'Growth ideas',
    support_growthBody:
      '— new campaigns, better storytelling, or features that make donating and tracking impact easier.',
    support_partners: 'Partnerships',
    support_partnersBody: '— brands, creators, hospitals, or NGOs that share the mission and want to co-create reach or events.',
    support_build: 'Build & ship',
    support_buildBody:
      '— developers, designers, or volunteers who can help improve the site, wallet flows, or transparency tools.',
    support_spread: 'Spread the word',
    support_spreadBody:
      '— share on socials, invite communities, and point people to the public donation wallet and HKIDS.',
    mission_title: 'Mission — What is HopeKids?',
    mission_sub: 'A movement of hope — tap to read our full story.',
    mission_open: 'Open',
    transparency_title: 'Transparency',
    wallet_title: 'Public Donation Wallet',
    wallet_verify: 'Verify on Solscan ↗',
    wallet_verifyHint:
      'Inspect the public donation address on-chain (read-only). Direct HKIDS or SOL deposits to this address are passed through in full.',
    wallet_recent: 'Recent signatures',
    wallet_recentEmpty: 'No recent data (try again on the deployed site).',
    wallet_recentErr: 'Could not load activity.',
    contact_title: 'Contact the team',
    contact_body: 'Questions, partnerships, or support — email us. We respond to HopeKids-related messages.',
    footer_rights: 'HopeKids © 2026',
    footer_tagline: 'Trade crypto. Give hope.',
    faq_title: 'FAQ',
    faq_q1: 'What is HKIDS?',
    faq_a1:
      'HKIDS is the HopeKids token on Solana. When people buy or trade it, 3% of that activity is allocated as HKIDS tokens to the public donation wallet. Anyone can also send HKIDS or SOL to that wallet directly — the entire amount goes to the fundraiser.',
    faq_q2: 'What is the 3%, and where does it go?',
    faq_a2:
      'It is a 3% share of HKIDS trading activity, delivered as HKIDS tokens to the published donation wallet. It is not a cut of unrelated assets — it is how part of the token flow supports the fundraiser. You can verify every transfer on-chain.',
    faq_q3: 'Is the donation wallet public?',
    faq_a3:
      'Yes. The address is listed on this page. We do not hide it — transparency is the point.',
    faq_q4: 'How do I get HKIDS?',
    faq_a4:
      'Use the Buy / Jupiter link to swap SOL for HKIDS, or receive tokens from another wallet. Always double-check the mint address.',
    privacy_title: 'Privacy',
    privacy_p1:
      'This page is informational. We do not require an account to read it. If you email us, we use your address only to reply about HopeKids.',
    privacy_p2:
      'The site may use privacy-friendly analytics (e.g. Vercel) to understand traffic — no ads profile. You can use browser controls or extensions to limit tracking.',
    privacy_p3:
      'For EU/EEA users: you may request access or deletion of correspondence by contacting the team email below.',
    tools_lang: 'Language',
    tools_contrast: 'High contrast',
    tools_help: 'Shortcuts',
    tools_en: 'EN',
    tools_pl: 'PL',
    shortcuts_title: 'Keyboard shortcuts',
    shortcuts_esc: 'Close dialogs / modals',
    shortcuts_slash: 'Open this help panel',
    shortcuts_close: 'Close',
    copy_done: 'Copied to clipboard',
    copy_aria: 'Copy wallet address',
    copy_ariaDone: 'Copied',
    story_title: 'The HopeKids story',
    story_close: 'Close',
    email_aria: 'Email HopeKids at',
    timer_aria: 'Time remaining in this 30-day support window',
    section_fundraiserAria: 'Fundraiser spotlight and supporting the project',
    section_marketAria: 'HKIDS live market data from DexScreener',
    intro_aria: 'HopeKids introduction',
    spotlight_alt: 'Example HopeKids spotlight child (illustrative photo)',
    lang_picker_aria: 'Choose interface language',
  },
  pl: {
    nav_socialAria: 'Social media i wykresy',
    hero_title: 'HopeKids',
    hero_tagline: 'Wspieraj chore dzieci dzięki kryptowalutom.',
    hero_bodyBefore: 'Przy każdym handlu HKIDS,',
    hero_bodyPercent: '3%',
    hero_bodyAfter:
      'aktywności trafia jako tokeny HopeKids (HKIDS) do publicznego portfela zbiórki. Jeśli samodzielnie wyślesz HKIDS lub SOL na ten adres, cała kwota jest przekazywana na zbiórkę — bez potrąceń.',
    hero_buy: 'Kup HopeKids',
    hero_wallet: 'Zobacz portfel darowizn',
    stats_tokensSaved: 'Tokeny zebrane dla dzieci',
    stats_currentValue: 'Aktualna wartość',
    stats_txs: 'Transakcje wspierające dzieci',
    market_title: 'Rynek na żywo (DexScreener)',
    market_charts: 'Wykresy i para ↗',
    market_holders: 'Holderzy na DexScreener ↗',
    market_cap: 'Kapitalizacja',
    market_price: 'Cena',
    market_liq: 'Płynność',
    jupiter_title: 'Zamiana na Jupiter',
    jupiter_body:
      'Wymień SOL na HKIDS w jednym przejściu. Otwiera oficjalną zamianę Jupiter w nowej karcie — ten sam szlak co przycisk Kup.',
    jupiter_cta: 'Otwórz Jupiter ↗',
    fundraiser_title: 'Zbiórka',
    fundraiser_body:
      'Zbiórka HopeKids dla dzieci potrzebujących opieki. Udostępnij stronę, handluj HKIDS lub przelej HKIDS albo SOL na publiczny portfel — z obrotu 3% trafia jako HKIDS na ten portfel; bezpośrednie wpłaty są zaliczane w całości.',
    support_window: 'Okno wsparcia',
    support_cycle: 'Cykl 30 dni · najpierw godziny',
    support_title: 'Wesprzyj projekt',
    support_growth: 'Pomysły na rozwój',
    support_growthBody:
      '— nowe kampanie, lepszy storytelling lub funkcje ułatwiające darowizny i śledzenie efektów.',
    support_partners: 'Partnerstwa',
    support_partnersBody:
      '— marki, twórcy, szpitale lub NGO dzielące misję i chcące współtworzyć zasięg lub wydarzenia.',
    support_build: 'Budowa i wdrożenia',
    support_buildBody:
      '— deweloperzy, designerzy lub wolontariusze pomagający w stronie, portfelu i narzędziach transparentności.',
    support_spread: 'Dotrzyj ze słowem',
    support_spreadBody:
      '— udostępniaj w socialach, zapraszaj społeczności, wskazuj publiczny portfel darowizn i HKIDS.',
    mission_title: 'Misja — czym jest HopeKids?',
    mission_sub: 'Ruch nadziei — dotknij, by przeczytać całą historię.',
    mission_open: 'Otwórz',
    transparency_title: 'Transparentność',
    wallet_title: 'Publiczny portfel darowizn',
    wallet_verify: 'Sprawdź na Solscan ↗',
    wallet_verifyHint:
      'Podgląd publicznego adresu w łańcuchu (tylko odczyt). Bezpośrednie wpłaty HKIDS lub SOL na ten adres przechodzą w całości.',
    wallet_recent: 'Ostatnie podpisy',
    wallet_recentEmpty: 'Brak danych (spróbuj na wdrożonej stronie).',
    wallet_recentErr: 'Nie udało się wczytać aktywności.',
    contact_title: 'Kontakt z zespołem',
    contact_body: 'Pytania, partnerstwa lub wsparcie — napisz maila. Odpowiadamy w sprawach HopeKids.',
    footer_rights: 'HopeKids © 2026',
    footer_tagline: 'Handluj krypto. Dawaj nadzieję.',
    faq_title: 'FAQ',
    faq_q1: 'Czym jest HKIDS?',
    faq_a1:
      'HKIDS to token HopeKids w sieci Solana. Przy kupnie i handlu 3% tej aktywności jest rozliczane jako tokeny HKIDS na publiczny portfel zbiórki. Możesz też samodzielnie wysłać HKIDS lub SOL na ten adres — cała wpłata idzie na zbiórkę.',
    faq_q2: 'Co oznacza 3% i dokąd trafia?',
    faq_a2:
      'To 3% udziału z aktywności handlu HKIDS, przekazywane jako tokeny HKIDS na opublikowany portfel zbiórki. To nie jest potrącenie z innych aktywów — tak część obrotu tokenem wspiera zbiórkę. Każdy transfer możesz sprawdzić w łańcuchu.',
    faq_q3: 'Czy portfel darowizn jest publiczny?',
    faq_a3:
      'Tak. Adres jest na tej stronie. Nie ukrywamy go — o to chodzi w transparentności.',
    faq_q4: 'Jak zdobyć HKIDS?',
    faq_a4:
      'Użyj linku Kup / Jupiter, by zamienić SOL na HKIDS, lub otrzymaj tokeny z innego portfela. Zawsze sprawdź adres mint.',
    privacy_title: 'Prywatność',
    privacy_p1:
      'Ta strona ma charakter informacyjny. Nie wymaga konta. Jeśli napiszesz maila, używamy adresu tylko do odpowiedzi w sprawie HopeKids.',
    privacy_p2:
      'Strona może używać przyjaznej analityki (np. Vercel) do statystyk ruchu — bez profilu pod reklamy. Możesz ograniczyć śledzenie ustawieniami przeglądarki.',
    privacy_p3:
      'Dla użytkowników UE/EOG: możesz poprosić o dostęp lub usunięcie korespondencji przez e-mail zespołu poniżej.',
    tools_lang: 'Język',
    tools_contrast: 'Wysoki kontrast',
    tools_help: 'Skróty',
    tools_en: 'EN',
    tools_pl: 'PL',
    shortcuts_title: 'Skróty klawiszowe',
    shortcuts_esc: 'Zamyka okna / modale',
    shortcuts_slash: 'Otwiera ten panel pomocy',
    shortcuts_close: 'Zamknij',
    copy_done: 'Skopiowano do schowka',
    copy_aria: 'Kopiuj adres portfela',
    copy_ariaDone: 'Skopiowano',
    story_title: 'Historia HopeKids',
    story_close: 'Zamknij',
    email_aria: 'Napisz do HopeKids:',
    timer_aria: 'Pozostały czas w 30-dniowym oknie wsparcia',
    section_fundraiserAria: 'Zbiórka i wsparcie projektu',
    section_marketAria: 'Dane rynkowe HKIDS z DexScreener',
    intro_aria: 'Wprowadzenie HopeKids',
    spotlight_alt: 'Przykładowe zdjęcie dziecka w spotlight HopeKids (ilustracyjne)',
    lang_picker_aria: 'Wybierz język strony',
  },
  ru: {
    nav_socialAria: 'Соцсети и графики',
    hero_title: 'HopeKids',
    hero_tagline: 'Помогайте больным детям с помощью криптовалюты.',
    hero_bodyBefore: 'С каждой сделки HKIDS',
    hero_bodyPercent: '3%',
    hero_bodyAfter:
      'активности направляется токенами HopeKids (HKIDS) на публичный кошелёк для пожертвований. Если вы сами отправите HKIDS или SOL на этот адрес, вся сумма идёт в сбор — удержаний нет.',
    hero_buy: 'Купить HopeKids',
    hero_wallet: 'Кошелёк для пожертвований',
    stats_tokensSaved: 'Токены для детей',
    stats_currentValue: 'Текущая стоимость',
    stats_txs: 'Транзакций в поддержку детей',
    market_title: 'Рынок в реальном времени (DexScreener)',
    market_charts: 'Графики и пара ↗',
    market_holders: 'Холдеры на DexScreener ↗',
    market_cap: 'Рыночная капитализация',
    market_price: 'Цена',
    market_liq: 'Ликвидность',
    jupiter_title: 'Обмен на Jupiter',
    jupiter_body:
      'Обменяйте SOL на HKIDS в один шаг. Откроется официальный Jupiter в новой вкладке — тот же маршрут, что у кнопки «Купить».',
    jupiter_cta: 'Открыть Jupiter ↗',
    fundraiser_title: 'Сбор средств',
    fundraiser_body:
      'Сбор HopeKids для детей, нуждающихся в помощи. Поделитесь страницей, торгуйте HKIDS или переведите HKIDS/SOL на публичный кошелёк — при обмене 3% в HKIDS идут на этот кошелёк; прямые переводы зачисляются полностью.',
    support_window: 'Окно поддержки',
    support_cycle: '30-дневный цикл · сначала часы',
    support_title: 'Поддержать проект',
    support_growth: 'Идеи роста',
    support_growthBody:
      '— новые кампании, сильнее истории или функции, упрощающие пожертвования и отчётность.',
    support_partners: 'Партнёрства',
    support_partnersBody:
      '— бренды, авторы, больницы или НКО с той же миссией и совместными активностями.',
    support_build: 'Разработка',
    support_buildBody:
      '— разработчики, дизайнеры или волонтёры для сайта, кошельков и прозрачности.',
    support_spread: 'Расскажите другим',
    support_spreadBody:
      '— делитесь в соцсетях, зовите сообщества, указывайте на публичный кошелёк и HKIDS.',
    mission_title: 'Миссия — что такое HopeKids?',
    mission_sub: 'Движение надежды — нажмите, чтобы прочитать историю.',
    mission_open: 'Открыть',
    transparency_title: 'Прозрачность',
    wallet_title: 'Публичный кошелёк пожертвований',
    wallet_verify: 'Проверить на Solscan ↗',
    wallet_verifyHint:
      'Просмотр адреса в блокчейне (только чтение). Прямые депозиты HKIDS или SOL проходят полностью.',
    wallet_recent: 'Последние подписи',
    wallet_recentEmpty: 'Нет данных (попробуйте на опубликованном сайте).',
    wallet_recentErr: 'Не удалось загрузить активность.',
    contact_title: 'Связь с командой',
    contact_body: 'Вопросы, партнёрство или поддержка — напишите на почту. Отвечаем по теме HopeKids.',
    footer_rights: 'HopeKids © 2026',
    footer_tagline: 'Торгуй крипто. Дарь надежду.',
    faq_title: 'FAQ',
    faq_q1: 'Что такое HKIDS?',
    faq_a1:
      'HKIDS — токен HopeKids в сети Solana. При покупке и торговле 3% активности в виде HKIDS идут на публичный кошелёк. Можно отправить HKIDS или SOL напрямую — вся сумма идёт в сбор.',
    faq_q2: 'Что значит 3% и куда это идёт?',
    faq_a2:
      'Это 3% от торговой активности HKIDS в виде токенов на опубликованный кошелёк. Это не удержание с других активов — так часть оборота поддерживает сбор. Каждый перевод можно проверить в сети.',
    faq_q3: 'Публичен ли кошелёк?',
    faq_a3:
      'Да. Адрес на этой странице. Мы его не скрываем — в этом смысл прозрачности.',
    faq_q4: 'Как получить HKIDS?',
    faq_a4:
      'Используйте «Купить» / Jupiter для обмена SOL на HKIDS или получите с другого кошелька. Всегда проверяйте mint.',
    privacy_title: 'Конфиденциальность',
    privacy_p1:
      'Страница информационная. Аккаунт не нужен. Если вы пишете на почту, адрес используем только для ответа по HopeKids.',
    privacy_p2:
      'Сайт может использовать простую аналитику (например Vercel) без рекламного профиля. Ограничения — в настройках браузера.',
    privacy_p3:
      'Для ЕС/ЕЭЗ: доступ или удаление переписки — через email команды ниже.',
    tools_lang: 'Язык',
    tools_contrast: 'Высокий контраст',
    tools_help: 'Сочетания',
    tools_en: 'EN',
    tools_pl: 'PL',
    shortcuts_title: 'Горячие клавиши',
    shortcuts_esc: 'Закрыть окна',
    shortcuts_slash: 'Открыть справку',
    shortcuts_close: 'Закрыть',
    copy_done: 'Скопировано',
    copy_aria: 'Копировать адрес',
    copy_ariaDone: 'Скопировано',
    story_title: 'История HopeKids',
    story_close: 'Закрыть',
    email_aria: 'Написать HopeKids:',
    timer_aria: 'Оставшееся время в 30-дневном окне',
    section_fundraiserAria: 'Сбор и поддержка проекта',
    section_marketAria: 'Рыночные данные HKIDS (DexScreener)',
    intro_aria: 'Введение HopeKids',
    spotlight_alt: 'Пример фото ребёнка в spotlight HopeKids (иллюстрация)',
    lang_picker_aria: 'Выберите язык интерфейса',
  },
  tr: {
    nav_socialAria: 'Sosyal medya ve grafikler',
    hero_title: 'HopeKids',
    hero_tagline: 'Kripto ile hasta çocuklara destek olun.',
    hero_bodyBefore: 'Her HKIDS işleminde,',
    hero_bodyPercent: '%3',
    hero_bodyAfter:
      'aktivite HopeKids (HKIDS) tokenları olarak halka açık bağış cüzdanına gider. Kendiniz HKIDS veya SOL gönderirseniz, tutarın tamamı bağışa gider — kesinti yoktur.',
    hero_buy: 'HopeKids satın al',
    hero_wallet: 'Bağış cüzdanını gör',
    stats_tokensSaved: 'Çocuklar için biriken tokenlar',
    stats_currentValue: 'Güncel değer',
    stats_txs: 'Çocuklara yardımcı işlemler',
    market_title: 'Canlı piyasa (DexScreener)',
    market_charts: 'Grafikler ve çift ↗',
    market_holders: 'DexScreener’da tutucular ↗',
    market_cap: 'Piyasa değeri',
    market_price: 'Fiyat',
    market_liq: 'Likidite',
    jupiter_title: 'Jupiter’da takas',
    jupiter_body:
      'SOL’u tek adımda HKIDS ile değiştirin. Resmi Jupiter takası yeni sekmede açılır — Satın Al ile aynı rota.',
    jupiter_cta: 'Jupiter’ı aç ↗',
    fundraiser_title: 'Bağış kampanyası',
    fundraiser_body:
      'Bakıma ihtiyacı olan çocuklar için HopeKids kampanyası. Sayfayı paylaşın, HKIDS işlemi yapın veya HKIDS/SOL gönderin — takasta %3 HKIDS bu cüzdana gider; doğrudan transferler tamamen yazılır.',
    support_window: 'Destek penceresi',
    support_cycle: '30 günlük döngü · önce saatler',
    support_title: 'Projeyi destekleyin',
    support_growth: 'Büyüme fikirleri',
    support_growthBody:
      '— yeni kampanyalar, daha iyi hikâye anlatımı veya bağış/etki takibini kolaylaştıran özellikler.',
    support_partners: 'Ortaklıklar',
    support_partnersBody:
      '— markalar, içerik üreticileri, hastaneler veya STK’lar; aynı misyon ve ortak etkinlikler.',
    support_build: 'Geliştir ve yayınla',
    support_buildBody:
      '— site, cüzdan akışları veya şeffaflık araçları için geliştirici, tasarımcı veya gönüllüler.',
    support_spread: 'Duyurun',
    support_spreadBody:
      '— sosyal medyada paylaşın, toplulukları davet edin, halka açık cüzdan ve HKIDS’e yönlendirin.',
    mission_title: 'Misyon — HopeKids nedir?',
    mission_sub: 'Umut hareketi — tam hikâye için dokunun.',
    mission_open: 'Aç',
    transparency_title: 'Şeffaflık',
    wallet_title: 'Halka açık bağış cüzdanı',
    wallet_verify: 'Solscan’de doğrula ↗',
    wallet_verifyHint:
      'Bağış adresini zincirde görüntüleme (salt okunur). Doğrudan HKIDS veya SOL yatırımları tam geçer.',
    wallet_recent: 'Son imzalar',
    wallet_recentEmpty: 'Veri yok (canlı sitede deneyin).',
    wallet_recentErr: 'Aktivite yüklenemedi.',
    contact_title: 'Ekiple iletişim',
    contact_body: 'Soru, ortaklık veya destek için e-posta gönderin. HopeKids konularında yanıtlıyoruz.',
    footer_rights: 'HopeKids © 2026',
    footer_tagline: 'Kripto takas et. Umut ver.',
    faq_title: 'SSS',
    faq_q1: 'HKIDS nedir?',
    faq_a1:
      'HKIDS, Solana üzerinde HopeKids tokenıdır. Alım ve işlemlerde aktivitenin %3’ü HKIDS olarak halka açık bağış cüzdanına gider. Doğrudan HKIDS veya SOL da gönderebilirsiniz — tamamı bağışa yazılır.',
    faq_q2: '%3 ne ve nereye gidiyor?',
    faq_a2:
      'HKIDS işlem aktivitesinin %3’ünün HKIDS token olarak yayınlanan bağış cüzdanına gitmesidir. Diğer varlıklardan kesinti değildir; akışın bir kısmı kampanyayı destekler. Her transfer zincirde doğrulanabilir.',
    faq_q3: 'Bağış cüzdanı herkese açık mı?',
    faq_a3:
      'Evet. Adres bu sayfada. Gizlemiyoruz — şeffaflık bunun için.',
    faq_q4: 'HKIDS nasıl alınır?',
    faq_a4:
      'Satın Al / Jupiter ile SOL’u HKIDS’e çevirin veya başka cüzdandan alın. Mint adresini her zaman kontrol edin.',
    privacy_title: 'Gizlilik',
    privacy_p1:
      'Sayfa bilgilendiricidir. Okumak için hesap gerekmez. E-posta gönderirseniz, yalnızca HopeKids yanıtı için kullanırız.',
    privacy_p2:
      'Site trafik için hafif analitik (ör. Vercel) kullanabilir — reklam profili yok. Tarayıcı kontrolleriyle sınırlayabilirsiniz.',
    privacy_p3:
      'AB/AEA kullanıcıları: yazışma erişimi veya silme için aşağıdaki ekip e-postası.',
    tools_lang: 'Dil',
    tools_contrast: 'Yüksek kontrast',
    tools_help: 'Kısayollar',
    tools_en: 'EN',
    tools_pl: 'PL',
    shortcuts_title: 'Klavye kısayolları',
    shortcuts_esc: 'Pencereleri kapat',
    shortcuts_slash: 'Yardım paneli',
    shortcuts_close: 'Kapat',
    copy_done: 'Panoya kopyalandı',
    copy_aria: 'Cüzdan adresini kopyala',
    copy_ariaDone: 'Kopyalandı',
    story_title: 'HopeKids hikâyesi',
    story_close: 'Kapat',
    email_aria: 'HopeKids’e e-posta:',
    timer_aria: '30 günlük destek penceresinde kalan süre',
    section_fundraiserAria: 'Kampanya ve proje desteği',
    section_marketAria: 'DexScreener’dan HKIDS piyasa verisi',
    intro_aria: 'HopeKids giriş',
    spotlight_alt: 'HopeKids spotlight örnek çocuk fotoğrafı (örnek)',
    lang_picker_aria: 'Arayüz dilini seçin',
  },
  de: {
    nav_socialAria: 'Social Media und Charts',
    hero_title: 'HopeKids',
    hero_tagline: 'Kranke Kinder mit Kryptowährung unterstützen.',
    hero_bodyBefore: 'Bei jedem HKIDS-Handel werden',
    hero_bodyPercent: '3%',
    hero_bodyAfter:
      'der Aktivität als HopeKids-Token (HKIDS) an die öffentliche Spenden-Wallet geleitet. Senden Sie selbst HKIDS oder SOL an diese Adresse, geht der volle Betrag an die Spendenaktion — ohne Abzüge.',
    hero_buy: 'HopeKids kaufen',
    hero_wallet: 'Spenden-Wallet ansehen',
    stats_tokensSaved: 'Für Kinder gesicherte Token',
    stats_currentValue: 'Aktueller Wert',
    stats_txs: 'Transaktionen für Kinder',
    market_title: 'Live-Markt (DexScreener)',
    market_charts: 'Charts & Paar ↗',
    market_holders: 'Inhaber auf DexScreener ↗',
    market_cap: 'Marktkapitalisierung',
    market_price: 'Preis',
    market_liq: 'Liquidität',
    jupiter_title: 'Tausch auf Jupiter',
    jupiter_body:
      'Tauschen Sie SOL gegen HKIDS in einem Schritt. Öffnet den offiziellen Jupiter-Tausch in einem neuen Tab — dieselbe Route wie beim Kaufen-Button.',
    jupiter_cta: 'Jupiter öffnen ↗',
    fundraiser_title: 'Spendenaktion',
    fundraiser_body:
      'Eine HopeKids-Aktion für Kinder, die Hilfe brauchen. Teilen Sie die Seite, handeln Sie HKIDS oder überweisen Sie HKIDS/SOL an die öffentliche Wallet — beim Swap fließen 3 % als HKIDS dorthin; Direktüberweisungen werden voll angerechnet.',
    support_window: 'Unterstützungsfenster',
    support_cycle: '30-Tage-Zyklus · zuerst Stunden',
    support_title: 'Projekt unterstützen',
    support_growth: 'Wachstumsideen',
    support_growthBody:
      '— neue Kampagnen, besseres Storytelling oder Funktionen für Spenden und Wirkungs-Tracking.',
    support_partners: 'Partnerschaften',
    support_partnersBody:
      '— Marken, Creator, Krankenhäuser oder NGOs mit derselben Mission und gemeinsamer Reichweite.',
    support_build: 'Entwickeln & ausrollen',
    support_buildBody:
      '— Entwickler, Designer oder Freiwillige für Website, Wallet-Flows oder Transparenz-Tools.',
    support_spread: 'Weitersagen',
    support_spreadBody:
      '— in Sozialen teilen, Communities einladen, auf die öffentliche Spenden-Wallet und HKIDS hinweisen.',
    mission_title: 'Mission — Was ist HopeKids?',
    mission_sub: 'Eine Bewegung der Hoffnung — tippen für die ganze Geschichte.',
    mission_open: 'Öffnen',
    transparency_title: 'Transparenz',
    wallet_title: 'Öffentliche Spenden-Wallet',
    wallet_verify: 'Auf Solscan prüfen ↗',
    wallet_verifyHint:
      'Öffentliche Adresse on-chain einsehen (nur lesen). Direkte HKIDS- oder SOL-Einzahlungen gehen vollständig durch.',
    wallet_recent: 'Letzte Signaturen',
    wallet_recentEmpty: 'Keine Daten (auf der Live-Site erneut versuchen).',
    wallet_recentErr: 'Aktivität konnte nicht geladen werden.',
    contact_title: 'Kontakt zum Team',
    contact_body: 'Fragen, Partnerschaften oder Support — schreiben Sie uns. Wir antworten zu HopeKids.',
    footer_rights: 'HopeKids © 2026',
    footer_tagline: 'Krypto handeln. Hoffnung geben.',
    faq_title: 'FAQ',
    faq_q1: 'Was ist HKIDS?',
    faq_a1:
      'HKIDS ist der HopeKids-Token auf Solana. Beim Kauf und Handel werden 3 % der Aktivität als HKIDS an die öffentliche Spenden-Wallet verteilt. Sie können auch direkt HKIDS oder SOL senden — der volle Betrag geht an die Aktion.',
    faq_q2: 'Was sind die 3 % und wohin gehen sie?',
    faq_a2:
      'Es ist ein Anteil von 3 % der HKIDS-Handelsaktivität, ausgezahlt als HKIDS an die veröffentlichte Spenden-Wallet. Kein Abzug von anderen Assets — so unterstützt ein Teil des Token-Flows die Aktion. Jede Überweisung ist on-chain prüfbar.',
    faq_q3: 'Ist die Spenden-Wallet öffentlich?',
    faq_a3:
      'Ja. Die Adresse steht auf dieser Seite. Wir verstecken sie nicht — Transparenz ist der Punkt.',
    faq_q4: 'Wie bekomme ich HKIDS?',
    faq_a4:
      'Nutzen Sie Kaufen / Jupiter, um SOL gegen HKIDS zu tauschen, oder erhalten Sie Token von einer anderen Wallet. Prüfen Sie immer die Mint-Adresse.',
    privacy_title: 'Datenschutz',
    privacy_p1:
      'Diese Seite ist informativ. Zum Lesen ist kein Konto nötig. Bei E-Mail nutzen wir Ihre Adresse nur zur Antwort zu HopeKids.',
    privacy_p2:
      'Die Site kann datenschutzfreundliche Analytics (z. B. Vercel) nutzen — kein Werbeprofil. Browser-Einstellungen können Tracking begrenzen.',
    privacy_p3:
      'Für EU/EWR: Auskunft oder Löschung der Korrespondenz über die Team-E-Mail unten.',
    tools_lang: 'Sprache',
    tools_contrast: 'Hoher Kontrast',
    tools_help: 'Tastenkürzel',
    tools_en: 'EN',
    tools_pl: 'PL',
    shortcuts_title: 'Tastenkürzel',
    shortcuts_esc: 'Dialoge schließen',
    shortcuts_slash: 'Hilfe öffnen',
    shortcuts_close: 'Schließen',
    copy_done: 'In die Zwischenablage kopiert',
    copy_aria: 'Wallet-Adresse kopieren',
    copy_ariaDone: 'Kopiert',
    story_title: 'Die HopeKids-Geschichte',
    story_close: 'Schließen',
    email_aria: 'HopeKids per E-Mail:',
    timer_aria: 'Verbleibende Zeit im 30-Tage-Unterstützungsfenster',
    section_fundraiserAria: 'Spendenaktion und Projektsupport',
    section_marketAria: 'HKIDS-Marktdaten von DexScreener',
    intro_aria: 'HopeKids-Einführung',
    spotlight_alt: 'Beispiel-Spotlight-Kind HopeKids (Illustrationsfoto)',
    lang_picker_aria: 'Oberflächensprache wählen',
  },
  hi: {
    nav_socialAria: 'सोशल मीडिया और चार्ट',
    hero_title: 'HopeKids',
    hero_tagline: 'क्रिप्टोकरेंसी से बीमार बच्चों की मदद करें।',
    hero_bodyBefore: 'हर HKIDS ट्रेड पर,',
    hero_bodyPercent: '3%',
    hero_bodyAfter:
      'गतिविधि HopeKids (HKIDS) टोकन के रूप में सार्वजनिक दान वॉलेट में जाती है। आप स्वयं HKIDS या SOL भेजें तो पूरी राशि दान में जाती है — कोई कटौती नहीं।',
    hero_buy: 'HopeKids खरीदें',
    hero_wallet: 'दान वॉलेट देखें',
    stats_tokensSaved: 'बच्चों के लिए सहेजे टोकन',
    stats_currentValue: 'वर्तमान मूल्य',
    stats_txs: 'बच्चों की मदद करने वाले लेनदेन',
    market_title: 'लाइव बाज़ार (DexScreener)',
    market_charts: 'चार्ट और पेयर ↗',
    market_holders: 'DexScreener पर होल्डर्स ↗',
    market_cap: 'बाज़ार पूंजीकरण',
    market_price: 'कीमत',
    market_liq: 'लिक्विडिटी',
    jupiter_title: 'Jupiter पर स्वैप',
    jupiter_body:
      'एक ही चरण में SOL को HKIDS से बदलें। आधिकारिक Jupiter स्वैप नई टैब में खुलता है — खरीदें बटन जैसा ही रास्ता।',
    jupiter_cta: 'Jupiter खोलें ↗',
    fundraiser_title: 'फंडरेज़र',
    fundraiser_body:
      'उन बच्चों के लिए HopeKids अभियान जिन्हें देखभाल चाहिए। पेज साझा करें, HKIDS ट्रेड करें या HKIDS/SOL सार्वजनिक वॉलेट में भेजें — स्वैप पर 3% HKIDS वहाँ जाता है; सीधे ट्रांसफर पूरे जुड़ते हैं।',
    support_window: 'समर्थन खिड़की',
    support_cycle: '30-दिन चक्र · पहले घंटे',
    support_title: 'प्रोजेक्ट का समर्थन करें',
    support_growth: 'विकास विचार',
    support_growthBody:
      '— नए अभियान, बेहतर कहानी, या दान और प्रभाव ट्रैक करना आसान बनाने वाली सुविधाएँ।',
    support_partners: 'साझेदारी',
    support_partnersBody:
      '— ब्रांड, क्रिएटर, अस्पताल या NGO जो मिशन साझा करें और साथ मिलकर पहुँच बनाएँ।',
    support_build: 'बनाएँ और लॉन्च करें',
    support_buildBody:
      '— डेवलपर, डिज़ाइनर या स्वयंसेवक साइट, वॉलेट फ्लो या पारदर्शिता टूल्स के लिए।',
    support_spread: 'फैलाएँ संदेश',
    support_spreadBody:
      '— सोशल पर साझा करें, समुदाय बुलाएँ, सार्वजनिक दान वॉलेट और HKIDS दिखाएँ।',
    mission_title: 'मिशन — HopeKids क्या है?',
    mission_sub: 'आशा की चलती हुई लहर — पूरी कहानी पढ़ने के लिए टैप करें।',
    mission_open: 'खोलें',
    transparency_title: 'पारदर्शिता',
    wallet_title: 'सार्वजनिक दान वॉलेट',
    wallet_verify: 'Solscan पर जाँचें ↗',
    wallet_verifyHint:
      'चेन पर सार्वजनिक पता देखें (केवल पढ़ने योग्य)। सीधे HKIDS या SOL जमा पूरी तरह जाते हैं।',
    wallet_recent: 'हाल के हस्ताक्षर',
    wallet_recentEmpty: 'कोई डेटा नहीं (लाइव साइट पर फिर कोशिश करें)।',
    wallet_recentErr: 'गतिविधि लोड नहीं हो सकी।',
    contact_title: 'टीम से संपर्क',
    contact_body: 'प्रश्न, साझेदारी या सहायता — ईमेल करें। हम HopeKids से जुड़े संदेशों का जवाब देते हैं।',
    footer_rights: 'HopeKids © 2026',
    footer_tagline: 'क्रिप्टो ट्रेड करें। आशा दें।',
    faq_title: 'सामान्य प्रश्न',
    faq_q1: 'HKIDS क्या है?',
    faq_a1:
      'HKIDS Solana पर HopeKids टोकन है। खरीद और ट्रेड पर गतिविधि का 3% HKIDS टोकन के रूप में सार्वजनिक दान वॉलेट में जाता है। आप सीधे HKIDS या SOL भी भेज सकते हैं — पूरी राशि अभियान में जाती है।',
    faq_q2: '3% क्या है और कहाँ जाता है?',
    faq_a2:
      'यह HKIDS ट्रेडिंग गतिविधि का 3% हिस्सा है, HKIDS टोकन के रूप में प्रकाशित दान वॉलेट में। अन्य संपत्तियों से कटौती नहीं — टोकन प्रवाह का हिस्सा अभियान को समर्थन देता है। हर ट्रांसफर चेन पर सत्यापित किया जा सकता है।',
    faq_q3: 'क्या दान वॉलेट सार्वजनिक है?',
    faq_a3:
      'हाँ। पता इस पेज पर है। हम इसे छिपाते नहीं — पारदर्शिता ही मकसद है।',
    faq_q4: 'HKIDS कैसे मिले?',
    faq_a4:
      'खरीदें / Jupiter लिंक से SOL को HKIDS में बदलें, या दूसरे वॉलेट से टोकन लें। हमेशा mint पता जाँचें।',
    privacy_title: 'गोपनीयता',
    privacy_p1:
      'यह पेज सूचनात्मक है। पढ़ने के लिए खाता नहीं चाहिए। ईमेल करने पर हम पता केवल HopeKids जवाब के लिए उपयोग करते हैं।',
    privacy_p2:
      'साइट ट्रैफ़िक के लिए हल्का विश्लेषण (जैसे Vercel) उपयोग कर सकती है — विज्ञापन प्रोफ़ाइल नहीं। ब्राउज़र से सीमित कर सकते हैं।',
    privacy_p3:
      'EU/EEA उपयोगकर्ता: नीचे दी टीम ईमेल से पत्राचार तक पहुँच या हटाने का अनुरोध कर सकते हैं।',
    tools_lang: 'भाषा',
    tools_contrast: 'उच्च कंट्रास्ट',
    tools_help: 'शॉर्टकट',
    tools_en: 'EN',
    tools_pl: 'PL',
    shortcuts_title: 'कीबोर्ड शॉर्टकट',
    shortcuts_esc: 'संवाद बंद करें',
    shortcuts_slash: 'यह सहायता पैनल खोलें',
    shortcuts_close: 'बंद करें',
    copy_done: 'क्लिपबोर्ड पर कॉपी हो गया',
    copy_aria: 'वॉलेट पता कॉपी करें',
    copy_ariaDone: 'कॉपी हो गया',
    story_title: 'HopeKids की कहानी',
    story_close: 'बंद करें',
    email_aria: 'HopeKids को ईमेल:',
    timer_aria: 'इस 30-दिन समर्थन खिड़की में बचा समय',
    section_fundraiserAria: 'फंडरेज़र स्पॉटलाइट और प्रोजेक्ट समर्थन',
    section_marketAria: 'DexScreener से HKIDS लाइव बाज़ार डेटा',
    intro_aria: 'HopeKids परिचय',
    spotlight_alt: 'HopeKids स्पॉटलाइट उदाहरण बच्चे की तस्वीर (चित्रण)',
    lang_picker_aria: 'इंटरफ़ेस भाषा चुनें',
  },
};

export function createT(locale) {
  const L = STRINGS[locale] || STRINGS.en;
  const fallback = STRINGS.en;
  return (key) => L[key] ?? fallback[key] ?? key;
}
